### ISSUE TITLE
Possible extension this method for general DNA language model

### ISSUE THREAD

**Issue by HelloWorldLTY** [p-koo/creme-nn#3]
Hi, thanks for your great work. I wonder if it is possible to apply this method for general sequence model like hyenaDNA or DNABERT, to explain the model performance. Moreover, since in your method you used many tests based on randomness, like randomly subsample sequence and random insert cres, I wonder if changing the random seeds will affect the results a lot or not. I do see sometimes the change will be huge for permutation test. Thanks.

**Comment by p-koo** [comment]
Thanks. You can generate sequence perturbations using CREME, but it's not clear whether that will help interpret hyenaDNA or DNABERT. I suggest looking at a few recent works:
1. https://doi.org/10.1101%2F2024.02.29.582810
2. https://www.biorxiv.org/content/10.1101/2024.07.27.605418v1
3. https://www.biorxiv.org/content/10.1101/2024.01.30.577970v1 

In terms of randomness, we typically shuffle 10-100 times and average predictions. You can think of this as a marginalization over the region that is randomized+averaged. We do note that selection of backgrounds could have some effect on the results due to finite sampling. Dinuc shuffle is the standard (for now).

**Comment by HelloWorldLTY** [comment]
Thanks for your answers, they are really helpful.

There also benchmarking papers argue that gLM performed better than CNN or ResNet,

https://arxiv.org/pdf/2311.12570

So it might be really task-specific argument.
